# fish completion for macos-health

complete -c macos-health -l once -d "Print one text snapshot and exit"
complete -c macos-health -l json -d "Print one structured JSON snapshot and exit"
complete -c macos-health -l stream -d "Stream newline-delimited JSON snapshots"
complete -c macos-health -l samples -x -d "Stop a stream after N samples"
complete -c macos-health -l duration -x -d "Stop collection after a duration"
complete -c macos-health -l record -r -d "Record private snapshots to a new file"
complete -c macos-health -l replay -r -d "Replay a recording"
complete -c macos-health -l serve -x -d "Serve loopback JSON, Prometheus, and health endpoints"
complete -c macos-health -l check -d "Return a health status exit code"
complete -c macos-health -l schema -d "Print the snapshot JSON Schema"
complete -c macos-health -l prometheus -d "Print Prometheus metrics"
complete -c macos-health -l interval -x -d "Set refresh interval (e.g. 1s, 500ms)"
complete -c macos-health -l no-color -d "Disable ANSI colors"
complete -c macos-health -l no-alt-screen -d "Keep dashboard output in the normal screen buffer"
complete -c macos-health -l ascii -d "Use ASCII-only charts and symbols"
complete -c macos-health -l redact -d "Hide computer name, hostname, and local addresses"
complete -c macos-health -l sensors -d "Read native Apple silicon sensors"
complete -c macos-health -l ports -d "Inspect local TCP listeners"
complete -c macos-health -l system-processes -d "Use ps for wider process visibility"
complete -c macos-health -l theme -x -a "ocean amber violet" -d "Set theme"
complete -c macos-health -l group -d "Group processes by owning application"
complete -c macos-health -l config -r -d "Use a preferences JSON file"
complete -c macos-health -l save-config -d "Save preferences and exit"
complete -c macos-health -l demo -d "Use synthetic telemetry for a safe demo"
complete -c macos-health -l version -d "Print version, commit, and build date"
complete -c macos-health -l help -d "Show usage help"
